steps:

- name: 'python:3.7'
  args:
<<<<<<< HEAD
  - 'make'
  - 'setup'

- name: 'python:3.7'
  args:
  - 'make'
  - 'install'

- name: 'python:3.7'
  args:
  - 'make'
  - 'test'

- name: 'python:3.7'
  args:
  - 'make'
  - 'lint'
=======
  - ['make','setup']
            #- ['make', 'setup']
      #    - ['make', 'install']
      #    - ['make', 'test']
      #- ['make', 'lint']
>>>>>>> 85980c5e0b459b3d54a27c579e390ae119eb4131
