steps:

- name: 'python:3.7'
  args:
  - 'make'
  - 'install'
- name: 'python:3.7'
  args:
  - 'make'
  - 'format'
- name: 'python:3.7'
  args:
  - 'make'
  - 'test'
- name: 'python:3.7'
  args:
  - 'make'
  - 'lint'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
