steps:

- name: 'python:3.7'
  args:
  - 'make'
  - 'setup'
- name: 'python:3.7'
  args:
  - 'make'
  - 'install'
- name: 'python:3.7'
  args:
  - 'make'
  - 'format'
- name: 'python:3.7'
  args:
  - 'make'
  - 'test'
- name: 'python:3.7'
  args:
  - 'make'
  - 'lint'
- name: "gcr.io/cloud-builders/gcloud"
  args: 
  - ['-c', 'export SENDGRID_API_KEY=$$SENDGRID_API_KEY']
  - ["app", "deploy"]
  secretEnv: ['SENDGRID_API_KEY']
availableSecrets:
  secretManager:
  - versionName: projects/388206994756/secrets/Send_Grid/versions/1
    env: 'SENDGRID_API_KEY'
